
networks:
  central_default:
    external: True

services:
  odoo:
    build: odoo
    container_name: roularta_odoo_14_tosc
    image: tosc-registry:443/roularta-test-odoo:latest
    environment:
      - MIGRATE=${MIGRATE}
      - PYTHONDONTWRITEBYTECODE=${PDWBC}
#      - LOCAL_USER_ID=${UID}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=$DB_NAME
      - DB_FILTER=${DB_FILTER}
      - ADMIN_PASSWD=${ADMIN_PASSWD}
      - RUNNING_ENV=${ENV}
      - LIST_DB=${LIST_DB}
#     - DEMO=False 
      - LIMIT_TIME_CPU=${LIMIT_TIME_CPU}
      - LIMIT_TIME_REAL=${LIMIT_TIME_REAL}
      - DB_HOST=${DB_HOST}
      - ADDONS_PATH=${ADDONS_PATH}
#      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=8069,8072/longpolling
      - KWKHTMLTOPDF_SERVER_URL=http://kwkhtmltopdf:8080
      - ODOO_REPORT_URL=http://localhost:8069
    ports:
      - 9014:8069
      - 9075:8072
    networks:
      - central_default
    volumes:
      - ./odoo/external-src:/odoo/external-src
      - ./odoo/links:/odoo/links
      - ./odoo/local-src:/odoo/local-src
      - ./data:/odoo/data/odoo
      - ./odoo/src/addons:/odoo/src/addons
      - ./odoo/src/odoo/addons:/odoo/src/odoo/addons
    #    command: ["odoo"]
    command: ["bash"]
    stdin_open: true
    tty: true
#    extra_hosts:
#      - "casa.tosc.nl:<xx.xx>"


