
networks:
  central_default:
    external: true

services:
  odoo:
    build: odoo
    image: tosc-registry:443/misset_odoo16_test:latest
    container_name: misset_odoo_16
    environment:
      - MIGRATE=${MIGRATE}
      - PYTHONDONTWRITEBYTECODE=${PDWBC}
#      - LOCAL_USER_ID=${UID}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=$DB_NAME
      - DB_FILTER=${DB_FILTER}
      - ADMIN_PASSWD=${ADMIN_PASSWD}
      - RUNNING_ENV=${ENV}
      - LIST_DB=${LIST_DB}
#     - DEMO=False
      - LIMIT_TIME_CPU=${LIMIT_TIME_CPU}
      - LIMIT_TIME_REAL=${LIMIT_TIME_REAL}
      - ADDONS_PATH=${ADDONS_PATH}
#      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=${HOST}
#      - VIRTUAL_PORT=8069,8072/longpolling
      - VIRTUAL_PORT=8069,8072/websocket
#      - KWKHTMLTOPDF_SERVER_URL=http://kwkhtmltopdf:8080
#      - ODOO_REPORT_URL=http://localhost:8069
#      - WORKERS=2  # [Uncomment for JobQueue]
#      - SERVER_WIDE_MODULES=web,queue_job # [Uncomment for JobQueue]

    ports:
      - 9016:8069
      - 9074:8072
    networks:
      - central_default
    volumes:
      - ./odoo/external-src:/odoo/external-src
      - ./odoo/links:/odoo/links
      - ./odoo/local-src:/odoo/local-src
      - ./data:/odoo/data/odoo
#      - ./odoo/src/addons:/odoo/src/odoo/addons
      - ./odoo/src/addons:/odoo/src/addons
      - ./odoo/src/odoo/addons:/odoo/src/odoo/addons
#      - ./odoo:/odoo
    command: ["bash"]
    stdin_open: true
    tty: true
#    extra_hosts:
#      - "casa.tosc.nl:10.225.12.141"
