#networks:
#    ${DEFAULT_NETWORK}:
#      external: true
#    backend-prod:
#      driver: bridge

  hoedoedeploy:
#    build: odoo
    image: ${IMAGENAME}
    environment:
      - MIGRATE=${MIGRATE}
      - PYTHONDONTWRITEBYTECODE=${PDWBC}
      - LOCAL_USER_ID=${UID}
      - DB_USER=${PGUSER}
      - DB_PASS=${PGPASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_FILTER=${DB_FILTER}
      - ADMIN_PASSWD=${ADMIN_PASSWD}
      - RUNNING_ENV=${ENV}
      - LIST_DB=${LIST_DB}
#      - DEMO=False
      - LIMIT_TIME_CPU=${LIMIT_TIME_CPU}
      - LIMIT_TIME_REAL=${LIMIT_TIME_REAL}
      - DB_HOST=${DB_HOST}
      - ADDONS_PATH=${ADDONS_PATH
#      - MARABUNTA_MODE=demo
#      - VIRTUAL_HOST=${HOST}}
#      - VIRTUAL_PORT=8069,8072/longpolling
    expose:
      - 8069
      - 8072
#    networks:
#      - club3d-base_default
#      - backend-prod
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
#    command: ["odoo"]
    command: ["bash"]
    stdin_open: true
    tty: true
version: '3'
