#!/bin/env bash
#
# Script to make software deployments in running docky containers easier
#
#
yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { "$@" || die "cannot $*"; }
IMAGE=$1
TAG=$2
HOME_FOLDER=$3

if [[ -z $1 ]]
    then
        docker ps -a
        echo "Which Image should be altered for deploy?"
        read IMAGE
        echo "Which Tag?"
        read TAG
            if [[ -z ${TAG} ]]
            then
                IMAGENAME=$IMAGE
            else
                IMAGENAME=${IMAGE}:${TAG}
            fi
fi
export IMAGENAME=$IMAGENAME

if [[ -z $3 ]]
    then
      read -p "Which path including home folder for this server? (default pwd) " HOME_PATH
fi
HOME_PATH="${HOME_PATH:=$(pwd)}"
HOME_FOLDER=$(basename $HOME_PATH)


set -e

OLDIMAGEID=$(docker images -q --filter=reference=${IMAGENAME})

read -p "Do you want to update the database from the command line? (y/n) " A
if [[ ${A} = "y" ]]
    then
        if  [[ ! -z $(docker ps -q -f "ancestor=${OLDIMAGEID}") ]]
            then
                try docker rm -f $(docker ps -q -f "ancestor=${OLDIMAGEID}")
                echo "Removed containers derived from Image ${OLDIMAGEID}."
        fi
        echo "If the connection to the database is not defined in docker-compose-hdd.yml, you
         have to do odoo --db_host=xxx.xxx.xxx.xxx --db_port=5432. With most servers there is a connection defined"

fi

try docker compose -f docker-compose-hdd.yml up -d
docker attach "${HOME_FOLDER}-hoedoedeploy-1"

read -p "Do you want to commit the changes you made to ${IMAGENAME}? (y/n): " B
if [[ ${B} = "y" ]]
    then
        try docker commit "${HOME_FOLDER}_hoedoedeploy_1" ${IMAGENAME}
    else
        read -p "Do you want to commit to a different image? (y/n): " D
    if [[ ${D} = "y" ]]
        then
            read -p "Please specify the IMAGE:TAG you want to commit to:" E
            echo "Are you sure you want to commit to $E?"
            read F
            if [[ ${F} = "y" ]]
                then
                    try docker commit "${HOME_FOLDER}_hoedoedeploy_1" $E
                    OLDIMAGEIDALT=$(docker images -q --filter=reference=${E})
            fi
    fi
fi

echo "Update-Container "${HOME_FOLDER}-hoedoedeploy-1" will now be deleted"
docker rm -f "${HOME_FOLDER}-hoedoedeploy-1"

if [[ ${B} = "y" ]]
    then
        echo "Do you want to push the changes you made to ${IMAGENAME}? (y/n)"
        read C
        if [[ ${C} = "y" ]]
            then
                try docker push ${IMAGENAME}
        fi
fi
if [[ ${F} = "y" ]]
    then
        echo "Do you want to push the changes you made to ${E}? (y/n)"
        read C
        if [[ ${C} = "y" ]]
            then
                try docker push $E
        fi
fi
if [[ ${B} = "y" ]] && [[ ${A} != "y" ]]
    then
        echo "Do you want to stop and remove running containers from image
        ${IMAGENAME}? (y/n)"
        read G
        if [[ ${G} = "y" ]]
            then
                try docker rm -f $(docker ps -q -f "ancestor=${OLDIMAGEID}")
                echo "Removed containers derived from Image ${OLDIMAGEID}."
        fi
elif [[ ${A} = "y" ]]
    then
        echo "Do you want to run \"docker compose up -d\"? (y/n)"
        read I
        if [[ ${I} = "y" ]]
            then
                cd ${HOME_PATH}
                try docker compose up -d
                docker ps
                echo "READY!!!"
        fi
fi